"""Generate the MJCF layered on top of the vendored YAM model.

Menagerie ships YAM as one file with the stock gripper fused into the arm. For
end effectors to be swappable, that file is split -- never edited -- into:

* ``assets/i2rt_yam/yam_arm.xml``: the arm alone, ending at link_6, the flange
  an end effector bolts to. Keeps link_6's wrist-motor mesh and its 0.367 kg
  inertia (mostly motor).
* ``assets/end_effectors/yam_linear/yam_linear.xml``: the stock linear gripper
  (fingers, linkage part, finger rails, grasp point, coupling, actuator) plus a
  D405-style camera on top, as one attachable body with its assets and default
  classes namespaced ``yam_linear_`` so they cannot collide with the arm's.

Menagerie also fuses the wrist-roll motor and the stock gripper's housing frame
into one mesh (model2__13). In link_6's frame the motor spans z -10.6..4 mm and
the housing reaches up to 60.5 mm; no triangle straddles the motor's top face, so it separates
them: the motor stays on the arm, the housing goes to the stock gripper.
Without the cut, any other end effector renders with the stock frame through it.
tests/test_composition.py proves arm + yam_linear reproduces upstream -- same
joints, actuators and masses, identical grasp-point kinematics.

``glasses.xml`` -- two water glasses -- is generated too: MuJoCo has no hollow
primitive, so each glass is a ring of wall boxes on a disc.

tests/test_yam_assets.py regenerates every file and fails if one drifts.
"""

from __future__ import annotations

import copy
import math
import struct
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

import numpy as np

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/build_yam_assets.py from teleop_sim/envs/yam_assets.py.\n"
    "     Do not edit by hand: change the generator and re-run it. -->\n"
)

# ------------------------------------------------------------------ cameras


def look_at_xyaxes(pos, target, up) -> str:
    """MJCF ``xyaxes`` for a camera at ``pos`` looking at ``target``.

    ``zaxis`` alone fixes only the viewing direction and leaves roll to
    MuJoCo, which is how Stage 1's first front camera ended up with a tilted
    horizon. Pinning right and up explicitly removes the ambiguity.
    """
    pos, target, up = (np.asarray(v, dtype=np.float64) for v in (pos, target, up))
    forward = target - pos
    forward /= np.linalg.norm(forward)
    right = np.cross(forward, up)
    norm = np.linalg.norm(right)
    if norm < 1e-9:
        raise ValueError("camera 'up' is parallel to its viewing direction")
    right /= norm
    true_up = np.cross(right, forward)
    return " ".join(f"{v:.6f}" for v in (*right, *true_up))


@dataclass(frozen=True)
class WristCamera:
    """D405-style eye-in-hand camera, in the frame of the gripper body.

    Part of the end effector, not the arm: a camera on the gripper travels with
    the gripper, and a different end effector has a different bracket.

    Measured, not inferred from where the finger bodies sit: the fingers slide
    along the gripper frame's x axis (37.4 mm each way), so the +y face is the
    top. At the arm's home (joint6 = 0) that face is world up and the fingers
    close horizontally -- the orientation for a side grasp on a standing glass.
    The end effector's root sits exactly at link_6, so these coordinates are
    the same in either frame.
    """

    parent_body: str = "yam_linear"
    mount_body: str = "wrist_d405"
    camera_name: str = "wrist"
    # Housing sits on the gripper's top face: the gripper mesh reaches
    # y = 47.4 mm under the camera's footprint, so the 23 mm-thick box is
    # centred at y = 60 mm with ~1 mm of clearance.
    mount_pos: tuple[float, float, float] = (0.0, 0.060, 0.040)
    # D405 enclosure: 42 x 42 x 23 mm, thin along the gripper's y.
    housing_half: tuple[float, float, float] = (0.021, 0.0115, 0.021)
    mass: float = 0.06
    # Lens on the housing's front face, aimed past the fingertips.
    lens_offset: tuple[float, float, float] = (0.003, 0.0, 0.022)
    aim_at_on_parent: tuple[float, float, float] = (0.0, 0.0, 0.17)
    # The D405's vertical field of view.
    fovy: float = 58.0

    def mjcf(self, indent: str) -> str:
        lens = np.asarray(self.lens_offset)
        target = np.asarray(self.aim_at_on_parent) - np.asarray(self.mount_pos)
        # Image "up" is the gripper's top, so the fingers sit at the bottom of the frame.
        xyaxes = look_at_xyaxes(lens, target, up=(0.0, 1.0, 0.0))
        hx, hy, hz = self.housing_half
        mx, my, mz = self.mount_pos
        lx, ly, lz = self.lens_offset
        i, j = indent, indent + "  "
        return (
            f'{i}<!-- D405-style wrist camera on top of the gripper (added by the generator). -->\n'
            f'{i}<body name="{self.mount_body}" pos="{mx:g} {my:g} {mz:g}" gravcomp="1">\n'
            f'{j}<inertial pos="0 0 0" mass="{self.mass:g}" '
            f'diaginertia="1.5e-05 1e-05 1e-05"/>\n'
            f'{j}<geom name="wrist_d405_visual" type="box" size="{hx:g} {hy:g} {hz:g}" '
            f'contype="0" conaffinity="0" group="2" rgba="0.12 0.12 0.13 1"/>\n'
            f'{j}<geom name="wrist_d405_lens" type="cylinder" size="0.006 0.001" '
            f'pos="{lx:g} {ly:g} {hz:g}" contype="0" conaffinity="0" group="2" '
            f'rgba="0.02 0.02 0.05 1"/>\n'
            f'{j}<geom name="wrist_d405_collision" type="box" size="{hx:g} {hy:g} {hz:g}" '
            f'group="3" mass="0"/>\n'
            f'{j}<camera name="{self.camera_name}" pos="{lx:g} {ly:g} {lz:g}" '
            f'xyaxes="{xyaxes}" fovy="{self.fovy:g}"/>\n'
            f"{i}</body>\n"
        )


# Mesh paths, relative to the file that references them: the arm's are relative
# to assets/i2rt_yam/, the stock gripper's to assets/end_effectors/yam_linear/.
ARM_UPSTREAM = "upstream/assets"
EE_UPSTREAM = "../../i2rt_yam/upstream/assets"
WRIST_MOTOR_MESH = "meshes/yam_wrist_motor.stl"
STOCK_FRAME_MESH = "meshes/stock_frame.stl"
EE_NAME = "yam_linear"
EE_PREFIX = f"{EE_NAME}_"
#: Physics the arm was validated with. 1/600 s makes a 30 Hz control period
#: exactly 20 substeps; upstream leaves MuJoCo's 0.002 default (16.67).
ARM_TIMESTEP = "0.0016666666666666668"

_FINGER_BODIES = ("link_left_finger", "link_right_finger")
#: The stock gripper's collision geoms on link_6: two finger rails and the
#: disc under its housing frame.
_GRIPPER_COLLISION_POSITIONS = ("0 0.039 0.052", "0 -0.039 0.052", "0 0.0 0.03")
_FUSED_MESH = "model2__13"
#: link_6-frame z the wrist motor ends at. A triangle lying wholly below it is
#: motor; anything reaching above is the stock gripper's housing, whose flat
#: side walls run from the motor face (4 mm) to the frame (44 mm) without a
#: single vertex in between.
_MOTOR_TOP_Z = 0.006


def _is_gripper_part(el: ET.Element) -> bool:
    """The stock gripper's pieces inside upstream's link_6."""
    if el.tag == "body":
        return el.get("name") in _FINGER_BODIES
    if el.tag == "geom":
        return el.get("mesh") == "model2__12" or el.get("pos") in _GRIPPER_COLLISION_POSITIONS
    if el.tag == "site":
        return el.get("name") == "grasp_site"
    return False


def _to_text(root: ET.Element) -> str:
    ET.indent(root, space="  ")
    return GENERATED_HEADER + ET.tostring(root, encoding="unicode") + "\n"


def _parse_upstream(upstream_xml: str) -> tuple[ET.Element, ET.Element]:
    root = ET.fromstring(upstream_xml)
    link6 = root.find(".//body[@name='link_6']")
    if link6 is None:
        raise ValueError("upstream yam.xml no longer has a link_6 body")
    found = [c for c in link6 if _is_gripper_part(c)]
    fused = [g for g in link6.findall("geom") if g.get("mesh") == _FUSED_MESH]
    if len(found) != 7 or len(fused) != 1:
        raise ValueError(
            "upstream yam.xml no longer matches the expected link_6 layout: found "
            f"{len(found)} of the 7 stock-gripper elements (2 fingers, linkage mesh, "
            "2 rails, housing disc, grasp_site) and {len(fused)} of 1 fused "
            "motor+frame mesh. Refusing to split an unrecognised model."
        )
    return root, link6


def _quat_matrix(wxyz: str) -> np.ndarray:
    w, x, y, z = (float(v) for v in wxyz.split())
    n = math.sqrt(w * w + x * x + y * y + z * z)
    w, x, y, z = w / n, x / n, y / n, z / n
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
        [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
        [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
    ])


_STL_RECORD = np.dtype([("n", "<f4", 3), ("v", "<f4", (3, 3)), ("a", "<u2")])


def read_stl(data: bytes) -> np.ndarray:
    """Binary STL -> (n, 3, 3) triangle vertices."""
    count = struct.unpack("<I", data[80:84])[0]
    if len(data) != 84 + 50 * count:
        raise ValueError("expected a binary STL")
    rec = np.frombuffer(data[84:], dtype=_STL_RECORD)
    return rec["v"].astype(np.float64)


def write_stl(triangles: np.ndarray, header: bytes = b"teleop_sim generated") -> bytes:
    rec = np.zeros(len(triangles), dtype=_STL_RECORD)
    rec["v"] = triangles
    e1, e2 = triangles[:, 1] - triangles[:, 0], triangles[:, 2] - triangles[:, 0]
    normals = np.cross(e1, e2)
    norm = np.linalg.norm(normals, axis=1, keepdims=True)
    rec["n"] = np.divide(normals, norm, out=np.zeros_like(normals), where=norm > 0)
    return header[:80].ljust(80, b"\0") + struct.pack("<I", len(triangles)) + rec.tobytes()


def split_fused_mesh(upstream_xml: str, stl: bytes) -> tuple[bytes, bytes]:
    """Cut model2__13 into (wrist motor, stock gripper frame).

    A triangle is motor only if it lies wholly below the motor's top face in
    link_6's frame, using the geom's own pose from the upstream XML. Both halves keep the
    original mesh coordinates, so each is used with that same geom pose.
    """
    _, link6 = _parse_upstream(upstream_xml)
    geom = next(g for g in link6.findall("geom") if g.get("mesh") == _FUSED_MESH)
    rot = _quat_matrix(geom.get("quat", "1 0 0 0"))
    pos = np.array([float(v) for v in geom.get("pos", "0 0 0").split()])
    tris = read_stl(stl)
    top = (tris @ rot.T + pos)[:, :, 2].max(axis=1)
    motor, frame = tris[top < _MOTOR_TOP_Z], tris[top >= _MOTOR_TOP_Z]
    if not len(motor) or not len(frame):
        raise ValueError("the cut through the fused wrist mesh left one side empty")
    return (
        write_stl(motor, b"YAM wrist-roll motor, split from Menagerie model2__13"),
        write_stl(frame, b"YAM stock gripper frame, split from Menagerie model2__13"),
    )


def build_arm(upstream_xml: str) -> str:
    """Upstream minus the stock gripper: the arm, ending at link_6."""
    root, _ = _parse_upstream(upstream_xml)
    root.set("model", "yam_arm")
    compiler = root.find("compiler")
    compiler.attrib.pop("meshdir", None)
    for mesh in root.find("asset").findall("mesh"):
        mesh.set("name", mesh.get("name") or Path(mesh.get("file")).stem)
        mesh.set("file", f"{ARM_UPSTREAM}/{mesh.get('file')}")

    option = root.find("option")
    if option is None:
        option = ET.Element("option")
        root.insert(1, option)
    option.set("timestep", ARM_TIMESTEP)

    link6 = root.find(".//body[@name='link_6']")
    for child in [c for c in link6 if _is_gripper_part(c)]:
        link6.remove(child)
    for tag in ("equality", "keyframe"):
        for el in root.findall(tag):
            root.remove(el)
    actuators = root.find("actuator")
    for act in [a for a in actuators if a.get("name") == "gripper"]:
        actuators.remove(act)
    worldbody = root.find("worldbody")
    for light in worldbody.findall("light"):     # lighting is the scene's job
        worldbody.remove(light)

    # The fused wrist mesh becomes the motor half; the frame half goes to the gripper.
    for geom in link6.findall("geom"):
        if geom.get("mesh") == _FUSED_MESH:
            geom.set("mesh", "yam_wrist_motor")
    assets = root.find("asset")
    for mesh in assets.findall("mesh"):
        if mesh.get("name") == _FUSED_MESH:
            mesh.set("name", "yam_wrist_motor")
            mesh.set("file", WRIST_MOTOR_MESH)

    used = {g.get("mesh") for g in root.iter("geom") if g.get("mesh")}
    for mesh in [m for m in assets.findall("mesh") if m.get("name") not in used]:
        assets.remove(mesh)
    return _to_text(root)


def build_linear_gripper(upstream_xml: str, camera: WristCamera | None = None) -> str:
    """The stock gripper as one attachable body, plus a wrist camera on top."""
    camera = camera or WristCamera()
    upstream, link6 = _parse_upstream(upstream_xml)

    ee = ET.Element("mujoco", model=EE_NAME)
    ET.SubElement(ee, "compiler", angle="radian")
    ee.append(copy.deepcopy(upstream.find("default")))

    parts = [copy.deepcopy(c) for c in link6 if _is_gripper_part(c)]
    fused = next(g for g in link6.findall("geom") if g.get("mesh") == _FUSED_MESH)
    frame = copy.deepcopy(fused)
    frame.set("mesh", "stock_frame")
    parts.insert(0, frame)
    used_meshes = {g.get("mesh") for p in parts for g in p.iter("geom") if g.get("mesh")}
    assets = ET.SubElement(ee, "asset")
    for asset in upstream.find("asset"):
        if asset.tag == "material":
            assets.append(copy.deepcopy(asset))
        elif asset.tag == "mesh" and Path(asset.get("file")).stem in used_meshes:
            mesh = copy.deepcopy(asset)
            mesh.set("name", Path(asset.get("file")).stem)
            mesh.set("file", f"{EE_UPSTREAM}/{asset.get('file')}")
            assets.append(mesh)
    ET.SubElement(assets, "mesh", name="stock_frame", file=STOCK_FRAME_MESH)

    worldbody = ET.SubElement(ee, "worldbody")
    body = ET.SubElement(worldbody, "body", name=EE_NAME, childclass="yam")
    # Explicit, negligible inertia: without it MuJoCo derives mass from the rail
    # collision geoms, which in upstream sit in link_6 where its explicit
    # inertial overrides them -- 52 g that upstream never had.
    ET.SubElement(body, "inertial", pos="0 0 0", mass="1e-6", diaginertia="1e-12 1e-12 1e-12")
    for part in parts:
        body.append(part)
    body.append(ET.fromstring(camera.mjcf("")))

    ee.append(copy.deepcopy(upstream.find("equality")))
    actuators = ET.SubElement(ee, "actuator")
    for act in upstream.find("actuator"):
        if act.get("name") == "gripper":
            actuators.append(copy.deepcopy(act))

    _namespace(ee, EE_PREFIX)
    return _to_text(ee)


def _namespace(root: ET.Element, prefix: str) -> None:
    """Prefix default classes, materials and meshes so the part can be attached
    next to any arm without a name collision."""
    classes = {d.get("class") for d in root.iter("default") if d.get("class")}
    for el in root.iter():
        for attr in ("class", "childclass"):
            if el.get(attr) in classes:
                el.set(attr, prefix + el.get(attr))
        if el.tag == "material":
            el.set("name", prefix + el.get("name"))
        elif el.get("material"):
            el.set("material", prefix + el.get("material"))
        if el.tag == "mesh":
            el.set("name", prefix + el.get("name"))
        elif el.get("mesh"):
            el.set("mesh", prefix + el.get("mesh"))


# ------------------------------------------------------------------ glasses


@dataclass(frozen=True)
class DrinkingGlass:
    """A plain tumbler.

    65 mm across, 100 mm tall, 3 mm walls. The diameter is set by the gripper,
    not by a catalogue: YAM's pads open to about 76 mm, and a 65 mm glass
    leaves roughly 5 mm of clearance on each side for a side grasp.
    """

    name: str
    pos: tuple[float, float]
    outer_radius: float = 0.0325
    height: float = 0.100
    wall: float = 0.003
    base: float = 0.006
    segments: int = 20
    # Soda-lime glass.
    density: float = 2500.0
    # Grip-friendly rather than glass-on-glass: the pads are the soft side of
    # the contact, and a slippery glass is not the problem this scene is for.
    friction: tuple[float, float, float] = (1.0, 0.01, 0.001)
    rgba: tuple[float, float, float, float] = (0.78, 0.88, 0.96, 0.35)

    def mjcf(self, indent: str = "    ") -> str:
        i, j = indent, indent + "  "
        rgba = " ".join(f"{c:g}" for c in self.rgba)
        fr = " ".join(f"{c:g}" for c in self.friction)
        contact = f'friction="{fr}" solimp="0.95 0.99 0.001" solref="0.004 1"'
        x, y = self.pos

        wall_mid = self.outer_radius - self.wall / 2
        # A little tangential overlap so adjacent segments leave no gaps.
        half_chord = wall_mid * math.tan(math.pi / self.segments) * 1.08
        half_height = (self.height - self.base) / 2
        z = self.base + half_height

        lines = [
            f'{i}<body name="{self.name}" pos="{x:g} {y:g} 0">',
            f'{j}<freejoint name="{self.name}_free"/>',
            f'{j}<geom name="{self.name}_base" type="cylinder" '
            f'size="{self.outer_radius:g} {self.base / 2:g}" pos="0 0 {self.base / 2:g}" '
            f'density="{self.density:g}" rgba="{rgba}" {contact}/>',
        ]
        for k in range(self.segments):
            theta = 2 * math.pi * k / self.segments
            cx, cy = wall_mid * math.cos(theta), wall_mid * math.sin(theta)
            qw, qz = math.cos(theta / 2), math.sin(theta / 2)
            lines.append(
                f'{j}<geom name="{self.name}_wall{k:02d}" type="box" '
                f'size="{self.wall / 2:g} {half_chord:.6f} {half_height:g}" '
                f'pos="{cx:.6f} {cy:.6f} {z:g}" quat="{qw:.6f} 0 0 {qz:.6f}" '
                f'density="{self.density:g}" rgba="{rgba}" {contact}/>'
            )
        lines.append(f"{i}</body>")
        return "\n".join(lines) + "\n"


#: Side by side in front of the arm, 110 mm centre to centre (a 45 mm gap
#: between walls). The arm faces +x at joint1 = 0; +y is the robot's left.
DEFAULT_GLASSES = (
    DrinkingGlass(name="glass_left", pos=(0.40, 0.055)),
    DrinkingGlass(name="glass_right", pos=(0.40, -0.055)),
)


def build_glasses(glasses: tuple[DrinkingGlass, ...] = DEFAULT_GLASSES) -> str:
    bodies = "".join(glass.mjcf() for glass in glasses)
    return (
        GENERATED_HEADER
        + '<mujoco model="glasses">\n  <worldbody>\n'
        + bodies
        + "  </worldbody>\n</mujoco>\n"
    )
