"""Generate the MJCF we layer on top of the vendored YAM model.

Two files are generated rather than hand-written:

* ``yam_follower.xml`` -- upstream ``yam.xml`` plus a D405-style camera mounted
  on top of the gripper. MuJoCo cannot add a camera to a body defined in an
  included file, so the alternative was forking upstream by hand; generating
  keeps ``upstream/`` byte-for-byte pristine and makes a Menagerie update a
  re-run instead of a merge.
* ``glasses.xml`` -- two water glasses. MuJoCo has no hollow primitive, so each
  glass is a ring of thin wall boxes on a disc base, which is tedious and
  error-prone to write out by hand forty times.

tests/test_yam_assets.py regenerates both and fails if the files on disk drift.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass

import numpy as np

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/build_yam_assets.py from teleop_sim/envs/yam_assets.py.\n"
    "     Do not edit by hand: change the generator and re-run it. -->\n"
)

# ------------------------------------------------------------------ cameras


def look_at_xyaxes(pos, target, up) -> str:
    """MJCF ``xyaxes`` for a camera at ``pos`` looking at ``target``.

    ``zaxis`` alone fixes only the viewing direction and leaves roll to
    MuJoCo, which is how Stage 1's first front camera ended up with a tilted
    horizon. Pinning right and up explicitly removes the ambiguity.
    """
    pos, target, up = (np.asarray(v, dtype=np.float64) for v in (pos, target, up))
    forward = target - pos
    forward /= np.linalg.norm(forward)
    right = np.cross(forward, up)
    norm = np.linalg.norm(right)
    if norm < 1e-9:
        raise ValueError("camera 'up' is parallel to its viewing direction")
    right /= norm
    true_up = np.cross(right, forward)
    return " ".join(f"{v:.6f}" for v in (*right, *true_up))


@dataclass(frozen=True)
class WristCamera:
    """D405-style eye-in-hand camera, in the frame of the gripper body.

    Measured, not inferred from where the finger bodies sit: the fingers slide
    along link_6's x axis (37.4 mm each way), so the +y face is the top of the
    gripper. At upstream's home (joint6 = 0) link_6 +y is world up and the
    fingers close horizontally -- the orientation for a side grasp on a
    standing glass.
    """

    parent_body: str = "link_6"
    mount_body: str = "wrist_d405"
    camera_name: str = "wrist"
    # Housing sits on the gripper's top face: the gripper mesh reaches
    # y = 47.4 mm under the camera's footprint, so the 23 mm-thick box is
    # centred at y = 60 mm with ~1 mm of clearance.
    mount_pos: tuple[float, float, float] = (0.0, 0.060, 0.040)
    # D405 enclosure: 42 x 42 x 23 mm, thin along the gripper's y.
    housing_half: tuple[float, float, float] = (0.021, 0.0115, 0.021)
    mass: float = 0.06
    # Lens on the housing's front face, aimed past the fingertips.
    lens_offset: tuple[float, float, float] = (0.003, 0.0, 0.022)
    aim_at_on_parent: tuple[float, float, float] = (0.0, 0.0, 0.17)
    # The D405's vertical field of view.
    fovy: float = 58.0

    def mjcf(self, indent: str) -> str:
        lens = np.asarray(self.lens_offset)
        target = np.asarray(self.aim_at_on_parent) - np.asarray(self.mount_pos)
        # Image "up" is the gripper's top, so the fingers sit at the bottom of the frame.
        xyaxes = look_at_xyaxes(lens, target, up=(0.0, 1.0, 0.0))
        hx, hy, hz = self.housing_half
        mx, my, mz = self.mount_pos
        lx, ly, lz = self.lens_offset
        i, j = indent, indent + "  "
        return (
            f'{i}<!-- D405-style wrist camera on top of the gripper (added by the generator). -->\n'
            f'{i}<body name="{self.mount_body}" pos="{mx:g} {my:g} {mz:g}" gravcomp="1">\n'
            f'{j}<inertial pos="0 0 0" mass="{self.mass:g}" '
            f'diaginertia="1.5e-05 1e-05 1e-05"/>\n'
            f'{j}<geom name="wrist_d405_visual" type="box" size="{hx:g} {hy:g} {hz:g}" '
            f'contype="0" conaffinity="0" group="2" rgba="0.12 0.12 0.13 1"/>\n'
            f'{j}<geom name="wrist_d405_lens" type="cylinder" size="0.006 0.001" '
            f'pos="{lx:g} {ly:g} {hz:g}" contype="0" conaffinity="0" group="2" '
            f'rgba="0.02 0.02 0.05 1"/>\n'
            f'{j}<geom name="wrist_d405_collision" type="box" size="{hx:g} {hy:g} {hz:g}" '
            f'group="3" mass="0"/>\n'
            f'{j}<camera name="{self.camera_name}" pos="{lx:g} {ly:g} {lz:g}" '
            f'xyaxes="{xyaxes}" fovy="{self.fovy:g}"/>\n'
            f"{i}</body>\n"
        )


def build_follower(upstream_xml: str, camera: WristCamera | None = None) -> str:
    """Upstream yam.xml with a wrist camera, and mesh paths fixed for our layout."""
    camera = camera or WristCamera()
    text = upstream_xml

    # meshdir resolves against the *top-level* model file, not the included
    # one, and our scenes sit one directory above upstream/.
    text, count = re.subn(r'meshdir="assets"', 'meshdir="upstream/assets"', text)
    if count != 1:
        raise ValueError("expected exactly one meshdir='assets' in upstream yam.xml")

    text = text.replace('<mujoco model="yam_v0">', '<mujoco model="yam_follower">', 1)

    anchor = re.search(r'( *)<site name="grasp_site"[^>]*/>\n', text)
    if anchor is None or f'name="{camera.parent_body}"' not in text:
        raise ValueError("upstream yam.xml no longer has the grasp_site anchor on link_6")
    text = text[: anchor.end()] + camera.mjcf(anchor.group(1)) + text[anchor.end() :]

    return GENERATED_HEADER + text


# ------------------------------------------------------------------ glasses


@dataclass(frozen=True)
class DrinkingGlass:
    """A plain tumbler.

    65 mm across, 100 mm tall, 3 mm walls. The diameter is set by the gripper,
    not by a catalogue: YAM's pads open to about 76 mm, and a 65 mm glass
    leaves roughly 5 mm of clearance on each side for a side grasp.
    """

    name: str
    pos: tuple[float, float]
    outer_radius: float = 0.0325
    height: float = 0.100
    wall: float = 0.003
    base: float = 0.006
    segments: int = 20
    # Soda-lime glass.
    density: float = 2500.0
    # Grip-friendly rather than glass-on-glass: the pads are the soft side of
    # the contact, and a slippery glass is not the problem this scene is for.
    friction: tuple[float, float, float] = (1.0, 0.01, 0.001)
    rgba: tuple[float, float, float, float] = (0.78, 0.88, 0.96, 0.35)

    def mjcf(self, indent: str = "    ") -> str:
        i, j = indent, indent + "  "
        rgba = " ".join(f"{c:g}" for c in self.rgba)
        fr = " ".join(f"{c:g}" for c in self.friction)
        contact = f'friction="{fr}" solimp="0.95 0.99 0.001" solref="0.004 1"'
        x, y = self.pos

        wall_mid = self.outer_radius - self.wall / 2
        # A little tangential overlap so adjacent segments leave no gaps.
        half_chord = wall_mid * math.tan(math.pi / self.segments) * 1.08
        half_height = (self.height - self.base) / 2
        z = self.base + half_height

        lines = [
            f'{i}<body name="{self.name}" pos="{x:g} {y:g} 0">',
            f'{j}<freejoint name="{self.name}_free"/>',
            f'{j}<geom name="{self.name}_base" type="cylinder" '
            f'size="{self.outer_radius:g} {self.base / 2:g}" pos="0 0 {self.base / 2:g}" '
            f'density="{self.density:g}" rgba="{rgba}" {contact}/>',
        ]
        for k in range(self.segments):
            theta = 2 * math.pi * k / self.segments
            cx, cy = wall_mid * math.cos(theta), wall_mid * math.sin(theta)
            qw, qz = math.cos(theta / 2), math.sin(theta / 2)
            lines.append(
                f'{j}<geom name="{self.name}_wall{k:02d}" type="box" '
                f'size="{self.wall / 2:g} {half_chord:.6f} {half_height:g}" '
                f'pos="{cx:.6f} {cy:.6f} {z:g}" quat="{qw:.6f} 0 0 {qz:.6f}" '
                f'density="{self.density:g}" rgba="{rgba}" {contact}/>'
            )
        lines.append(f"{i}</body>")
        return "\n".join(lines) + "\n"


#: Side by side in front of the arm, 110 mm centre to centre (a 45 mm gap
#: between walls). The arm faces +x at joint1 = 0; +y is the robot's left.
DEFAULT_GLASSES = (
    DrinkingGlass(name="glass_left", pos=(0.40, 0.055)),
    DrinkingGlass(name="glass_right", pos=(0.40, -0.055)),
)


def build_glasses(glasses: tuple[DrinkingGlass, ...] = DEFAULT_GLASSES) -> str:
    bodies = "".join(glass.mjcf() for glass in glasses)
    return (
        GENERATED_HEADER
        + '<mujoco model="glasses">\n  <worldbody>\n'
        + bodies
        + "  </worldbody>\n</mujoco>\n"
    )
